import type { Appointment } from "../types/dashboard";

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: "1",
    customerName: "Melisa Yılmaz",
    customerPhone: "+90 532 765 43 21",
    serviceName: "Saç Kesimi & Fön",
    category: "Kadın",
    date: "21 Mayıs 2026",
    time: "14:30",
    duration: "45 dk",
    staffName: "Elif Şimşek",
    price: 350,
    status: "Bekliyor",
    paymentStatus: "Ödeme Alındı",
  },
  {
    id: "2",
    customerName: "Can Tekin",
    customerPhone: "+90 505 123 45 67",
    serviceName: "Damat Tıraşı",
    category: "Erkek",
    date: "22 Mayıs 2026",
    time: "11:00",
    duration: "90 dk",
    staffName: "Ahmet Yılmaz",
    price: 1200,
    status: "Bekliyor",
    paymentStatus: "Ödeme Alındı",
  },
  {
    id: "3",
    customerName: "Ayşe Demir",
    customerPhone: "+90 544 987 65 43",
    serviceName: "Ombre",
    category: "Kadın",
    date: "18 Mayıs 2026",
    time: "10:00",
    duration: "180 dk",
    staffName: "Selin Kaya",
    price: 1800,
    status: "İptal",
    paymentStatus: "İptal Edildi",
    cancelReason: "Müşteri talebi doğrultusunda iptal edildi.",
  },
  {
    id: "4",
    customerName: "Merve Kaya",
    customerPhone: "+90 533 444 55 66",
    serviceName: "Saç Boyama",
    category: "Kadın",
    date: "19 Mayıs 2026",
    time: "16:00",
    duration: "120 dk",
    staffName: "Elif Şimşek",
    price: 950,
    status: "Tamamlandı",
    paymentStatus: "Hesaba Aktarıldı",
  },
];

export const CANCEL_OPTIONS = [
  "Müşteri randevuya gelmedi / ulaşılamıyor",
  "Müşteri talebi doğrultusunda iptal edildi",
  "Salondan kaynaklı zorunlu program değişikliği",
  "Diğer (Gerekçe Belirtiniz)",
];
