export const STAFF_ROLES = [
  { id: "sac_kesim", label: "Saç Kesim & Tasarım Uzmanı" },
  { id: "renklendirme", label: "Renklendirme & Boya Sihirbazı" },
  { id: "sac_uzatma", label: "Micro Kaynak & Saç Uzatma Uzmanı" },
  { id: "sac_bakim", label: "Saç Bakım & Keratin Uzmanı" },
  { id: "topuz_gelin", label: "Gelin Saçı & Topuz Tasarım Artist" },
  { id: "makyaj", label: "Profesyonel Makyaj & Kirpik Artist" },
  { id: "kalici_makyaj", label: "Kalıcı Makyaj & Microblading Uzmanı" },
  { id: "tirnak_manikur", label: "Protez Tırnak & Nail Art Uzmanı" },
  { id: "pedikur_bakim", label: "Medikal Pedikür & Ayak Bakım Uzmanı" },
  { id: "kas_tasarim", label: "Kaş Laminasyonu & İpek Kirpik Uzmanı" },
  { id: "cilt_bakim", label: "Medikal Cilt Bakımı & Estetisyen" },
  { id: "salon_koordinator", label: "Salon Koordinatörü & Resepsiyonist" },
  { id: "bolgesel_incelme", label: "Bölgesel İncelme & Vücut Şekillendirme Uzmanı" },
  { id: "lazer_epilasyon", label: "Lazer Epilasyon Teknisyeni" },
  { id: "masaj_terapi", label: "Masöz & Sertifikalı Masaj Terapisti" },
  { id: "solaryum_bronzluk", label: "Solaryum & Sprey Tan Bronzlaşma Uzmanı" },
  { id: "sac_simulasyon", label: "Saç Simülasyonu & Saç Pigmentasyon Artist" },
  { id: "salon_asistani", label: "Salon Asistanı & Junior Kuaför" },
  { id: "hijyen_servis", label: "Salon Hijyen & İkram Sorumlusu" }
];